"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def calc_even_sum(n):
    pass


def main():
    print("Sum of even-valued fibonacci numbers below 4 mln value is {}".format(calc_multiples_sum(1000)))

if __name__ == '__main__':
    main()
